/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.2.1/userguide/multi_project_builds.html
 */

rootProject.name = "rhs-assignment"
pluginManagement {
    buildscript {
        repositories {
            mavenLocal()
            mavenCentral()
            jcenter()
            google()
            gradlePluginPortal()
            maven {
                url = uri("https://dl.bintray.com/jetbrains/intellij-plugin-service/")
            }
        }
        dependencies {
            classpath("com.sun.istack:istack-commons-runtime:3.0.10")
        }
    }
    plugins {
        `java-library`
        application
        id("com.github.johnrengelman.shadow") version "6.0.0"
        id("org.jetbrains.intellij") version "0.4.24"

    }

    repositories {
        mavenLocal()
        mavenCentral()
        jcenter()
        google()
        gradlePluginPortal()
        maven {
            url = uri("https://dl.bintray.com/jetbrains/intellij-plugin-service/")
        }
    }
}
include(":kotlin-plugin")
include(":ide-plugin")
//include(":gradle-plugin")
include(":sample")
project(":kotlin-plugin").name = "rhs-assignment-compiler-plugin"
//project(":ide-plugin").name = "rhs-assignment-ide-plugin"
val mainProj = this
includeBuild("gradle-plugin") {
    dependencySubstitution {
        substitute(module("io.github.shekhei:rhs-assignment-gradle-plugin"))
                .with(project(":"))
    }
}